const orderStates = {
  INITIAL: 'INITIAL',
  PAYMENT_ININITIALIZED: 'PAYMENT_ININITIALIZED',
  PAYMENT_IN_PROGRESS: 'PAYMENT_IN_PROGRESS',
  PAYMENT_FINISHED: 'PAYMENT_FINISHED',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  ARCHIVED: 'ARCHIVED',
  ERROR: 'ERROR'
}

export default orderStates

